version: '3.8'   # Можно оставить, но не критично

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=foodbasket
      - SECRET_KEY=your-secret-key-here      # Обязательно синхронизируйте с config.py и .env
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256
    restart: unless-stopped
    networks:
      - backend

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: foodbasket
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_TCP_PORT: 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
